name = "EventTimeSeries"
uuid = "7b3b0897-f5bf-4bda-bc97-1b6cec243418"
authors = ["Jon Alm Eriksen <jon.alm.eriksen@protonmail.com>"]
version = "0.2.0"

[deps]
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[compat]
PrettyTables = "0.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
